# Generated by Django 2.0.6 on 2018-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobd',
            fields=[
                ('jd_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
    ]
